### ISSUE TITLE
Let azata's spells that restore abilities and spell slots actually do restore them

### ISSUE THREAD

**Issue by styx0412** [Vek17/TabletopTweaks-Base#206]
Some of azata's defining spells, spells which restore all companion's abilities and spell slots, are not working properly at the moment. They simply have no effect. Those spells are: **Joy of Life, Second Breath, Hero never surrender.** If those spells work as intended, Azata path would regain a huge part of its own power.

**Comment by styx0412** [comment]
> I've already patched second breath, the others I have not gotten to yet.

ah yeees I noticed your update logs and thank you for fixing believe in yourself!  I suppose I just need to wait till you work on the other two spells then : )

**Comment by Vek17** [comment]
This was completed a while back and never closed
