### ISSUE TITLE
Cannot apply persistent metamagic to some spells

### ISSUE THREAD

**Issue by Kbee38** [Vek17/TabletopTweaks-Base#21]
Don't know it is main game bug or mod's bug, but I can't apply persistent metamagic to grease spell and create pit spell, although they require saving throw to resist their effect.
![Persistent](https://user-images.githubusercontent.com/77181975/132444760-4a25572a-38d0-49b1-bd19-229ceff39b90.png)

**Comment by Vek17** [comment]
So as Grease is currently implemented this is not possible to fix as it doesn't force saving throws in a way that would actually work with the metamagic. The same is true of similar effects like stinking cloud. While it is something that I may potentially address at some point it is fairly low on my list atm. Every spell like this essentially needs to be fully re implemented to make this work correctly.
