### ISSUE TITLE
Gold Dragon prequiteless feats work poorly with many of the added feats.

### ISSUE THREAD

**Issue by MorvarchPrincess** [Vek17/TabletopTweaks-Base#225]
**Describe the bug**
Multiple feats added by this mod act strangely when picked up with Dragon Feats (aka the requirement less feat picks). You can pick up things like Extra Discovery ect.

Some examples of things I found:
Extra Discovery, Grand Mutagen gives you the ability but it doesn't actually do anything unless you have legit mutagen from another source
High level feats on feat chains like greater vital strike don't allow you take mythic vital strike.
Things like advanced weapon training and similar seem to be based off of you being level 1, so they don't do much.

**To Reproduce**
1. Become a gold dragon
2. Pick any of the above mentioned style of feats with your mythic rank 9 picks
3. Test out abilities

**Expected behavior**
Them to work as you'd think when you pick them up

**Additional context**
This frankly seems like a lot of effort to fix for little gain, so low priority I'd assume. but mentioning it here in case it hasn't been found yet

**Comment by Vek17** [comment]
this is a huge can of worms that basically would require reimplementing every feat to be completely independent of all other feats. As it stands I am simply not going to fix because the required work is dramatically larger than actual impact of the problem.
