### ISSUE TITLE
Shield Master gives the enhancement bonus to attack from shields twice in some instances

### ISSUE THREAD

**Issue by ObsidianRazor** [Vek17/TabletopTweaks-Base#308]
So, Shield Master should give you the Enhancement Bonus of a magic shield to attack, plus, negating the two-weapon fighting penalty.

The game seems to do this by giving you +2 to hit with the shield plus it's enhancement, so with a +5 shield, Shield Master should give you +7 to hit.

However, some shields seem to give you their enhancement to attack on top of this. I think it's the spiked shields as they have this as an inherent property. 

"The Undying Love of the Hopebringer" is one example of these shields.

**Comment by 1onepower** [comment]
it's a bug in the original game. should be a feature request.

**Comment by pheonix99** [comment]
It's the spiked shields, yes.

Shield Of Holy Thorn does this too.

**Comment by Vek17** [comment]
I believe this has been fixed with the new enchantment handling added for armor
