### ISSUE TITLE
Fix Loremaster Spell Selection

### ISSUE THREAD

**Issue by 666lumberjack** [Vek17/TabletopTweaks-Base#32]
The Loremaster Prestige class should allow you to pick one Wizard, Cleric or Druid spell when learning a Secret, but these options are not currently selectable. It would be great if this was fixed. 

EDIT: Apparently you also don't get additional spell progression from the first level as intended, but it works fine for levels 2+.

**Comment by Vek17** [comment]
Fixed now both by me and owlcat in different ways
