### ISSUE TITLE
Scorching ray (cold) and burning hands (cold) from water bloodline do not qualify for rime spell

### ISSUE THREAD

**Issue by Reginude** [Vek17/TabletopTweaks-Base#371]
**Describe the bug**
Scorching ray (cold) and burning hands (cold) from water bloodline do not qualify for rime spell

**To Reproduce**
See attached picture.

**Expected behavior**
To be able to apply rime spell to scorning ray (cold) and burning hands (cold)

**Screenshots**
<img width="1914" alt="Rime spell not working on Scorching ray (cold) or burning hands (cold)" src="https://user-images.githubusercontent.com/92412754/150647108-25f20b45-e959-4ee5-8272-7150eb04212d.png">

**Additional context**
NA

**Comment by Vek17** [comment]
This was an oversight, will be fixed in next release

**Comment by Reginude** [comment]
Thanks :)

**Comment by Reginude** [comment]
Do you know if splash damage from bolstered spell will allow you to apply rime spell, or will it only proc on direct damage? Side not, any idea when next release will be? Eager to try this out. Thanks for all the great work!

**Comment by Vek17** [comment]
Bolster probably will splash rime? Actually haven't tested but it should in theory I think. Next release will be for the 1.2 beta release which according to Owlcat Starrok should be in a few days/maybe a week.
