### ISSUE TITLE
change to bolster spell to +2 can't be turned off

### ISSUE THREAD

**Issue by templer10** [Vek17/TabletopTweaks-Base#379]
i have a wizard with bolster spell and favorite metamagic bolster spell. i turned off the change to make it +2 and it is still +2 - or +1 with favorite metamagic bolster spell.

i attached a save. to reproduce just try to metamagic any spell with bolster and it will be +2 despite having favorite metamagic - or you can respec the mythic and it will be +2. 
[Manual_175_bolster_spell_bug.zip](https://github.com/Vek17/WrathMods-TabletopTweaks/files/7937524/Manual_175_bolster_spell_bug.zip)

**Comment by Vek17** [comment]
I am not able to reproduce, Nor do I see how this could be the case in code. You WILL need to rebuild the meta magic spells if you prepared them as a +2 cost instead of a +1, though the same is true if you prepared as +1 instead of +2.

**Comment by templer10** [comment]
i tried rebuilding spells, tried a full respec. despite having canceled the fix to bolster it's +2 or +1 with favorite.

**Comment by Vek17** [comment]
And to clarify you have disabled this setting, saved (this should happen automatically but do it manually to be safe) and restarted the game.
![image](https://user-images.githubusercontent.com/2959420/151076340-32fb2bba-703c-41c4-8a82-b1808b9ff059.png)

There are other fixes to bolster in Fixes that do not affect cost

**Comment by templer10** [comment]
yes i disabled this setting.

**Comment by Vek17** [comment]
Then I have no idea but it is not TTT. No code runs involving bolster cost adjustment if that setting is disabled. Unfortunately I cannot load your save, I assume due to other mods, but in all my test files it works exactly as expected.
