### ISSUE TITLE
Mounted charge attacks with spirited charge attacking an extra time

### ISSUE THREAD

**Issue by yamilonewolf** [Vek17/TabletopTweaks-Base#400]
**Describe the bug**
Charging while mounted attacks twice both are doubled by spirited charge
damage appears as 
1d8 + 10 (x2)=  28
1d8+10 (x2) = 24
52
**To Reproduce**

feats:
mounted combat
power attack
spirited charge

**Expected behavior**
damage should roll once and be doubled

**Comment by Vek17** [comment]
This has been fixed as far as I am aware
