### ISSUE TITLE
new idealize arcane discovery doesnt work with enlarge or reduce person or after a loading screen

### ISSUE THREAD

**Issue by lanis404** [Vek17/TabletopTweaks-Base#412]
Don't know if this is intended. 
I have also noticed that it sometimes doesn't work with the normal stat buffs like bull's strength, cats grace no discernible reason.
Not high level enough to test with other buffs like legendary proportions, frightful aspect or the dragon forms yet.

update:
after a little bit of testing it seems that idealize will work on initial cast but as soon as you hit a loading screen, the buff goes back to only +4 for everyone except for the caster.
so for example, wizard with idealize casts bulls strength mass. everyone gets +6 str buff. after any loading screen, everyone goes back to +4 except for the wizard who stays at +6.

never works with enlarge or reduce. they are always still +2

**Comment by lanis404** [comment]
after a little bit of testing it seems that idealize will work on initial cast but as soon as you hit a loading screen, the buff goes back to only +4 for everyone except for the caster. 
so for example, wizard with idealize casts bulls strength mass. everyone gets +6 str buff. after any loading screen, everyone goes back to +4 except for the wizard who stays at +6. 

never works with enlarge or reduce. they are always still +2

**Comment by Vek17** [comment]
Reduce/enlarge don't grant enhancement binus so they don't apply. Save
persistence is the result of an owlcat bug this patch that broke context
serialization, currently waiting for a fix on thier end as it broke quite a
few other systems.

**Comment by Vek17** [comment]
Just found a fix for the bug that was preventing Idealize from working correctly when loading from a saved game, so that will be fixed in the 1.3.0 release on Thursday

**Comment by lanis404** [comment]
awesome! i finally dont have to have a brown fur transmuter merc for the big stat buffs! still the most overpowered support class by far with the eventual +4 bonus stats to all buffs including things like legendary proportions.
