### ISSUE TITLE
Improved Incense Fog doesn't stack properly

### ISSUE THREAD

**Issue by CantripN** [Vek17/TabletopTweaks-Base#418]
Hey :)

So, Improved Incense Fog (an additional +1 attack/damage) doesn't add anything the first time you take it, and the 2nd time you do it becomes +2.

Basically, without it you're at +1, with 1 you're still at +1, and with 2 you're at +2.

Intended behavior is +1, then +2, then +3.

Please fix the game's bug? <3

**Comment by CantripN** [comment]
To clarify if unclear - those are abilities a Incense Synthesizer Alchemist gets and can pick as upgrades.

**Comment by Vek17** [comment]
This is currently fixed in my dev version and will be in the next release.
