### ISSUE TITLE
Homebrew Bolstered Spell +2 not customizable

### ISSUE THREAD

**Issue by Jusderai5in** [Vek17/TabletopTweaks-Base#420]
Cant turn off the homebrew change to bolstered spell (+1 to +2 spell level)

Kinda force up in the mod for a homebrew change.

**Comment by Vek17** [comment]
O.o The bolstered changes don't exist in this mod.

**Comment by Vek17** [comment]
Well the setting in 1.11.2 should work, I know it worked in all testing I did in that version which was fairly extensive. Other than that not much I can do about it.
