### ISSUE TITLE
Destructive Dispel (change) and Dispelling Attack are not working

### ISSUE THREAD

**Issue by PCDK** [Vek17/TabletopTweaks-Base#428]
If you enable the **Destructive Dispel** change from this mod and attack a unit with a Sneak Attack, that procs **Dispelling Attack** (Rouge or Alchemist get it), the modifier used is only your mental stat insted of your class level (as caster level).

What is wierd is that, in my tests, with my level 14 Vivisectionist when I attack someone with the **Destructive Dispel** change enabled i get **+3** (int modifier) but with it disabled i only get **+9**. I have no ider how that is calculated.

![image](https://user-images.githubusercontent.com/13593867/166148284-c2fcb6fd-ae32-44e5-8f6f-b2ee6f31c0d4.png)

**Comment by Vek17** [comment]
I don't understand the question, destructive dispel doesn't use you mental
stats at all.

**Comment by PCDK** [comment]
Hey vek, sorry if I did not explain my self well enough.

It is not that I am using the Destructive Dispel feat, it is when I turn on the destructive dispel change from the mod:
![image](https://user-images.githubusercontent.com/13593867/166149941-fe4d2de4-4c44-43ad-b2a2-ccb2df4bb936.png)

This makes the Dispelling Attack use mental stat modifier insted of class level.

**Comment by Vek17** [comment]
O.o this does not make sense to me they have no interaction at all. I guess
I'll test but I see no way these could possibly interact.

**Comment by Jandronicos** [comment]
I believe the dispelling attack fix also isn't working, or it  is enabled for me, but the modifier remains at 1, despite being character level 17. 1 would be due to taking one level of loremaster -> rogue talent -> dispelling attack to pick it up. So it is scaling based on the class level and not the character level as it should.

**Comment by Vek17** [comment]
This should be fully resolved in current so I am closing this

**Comment by Vek17** [comment]
The scaling is based on rogue level as it should be.
