### ISSUE TITLE
I think i might have done something wrong on installatio

### ISSUE THREAD

**Issue by oddball250** [Vek17/TabletopTweaks-Base#431]
I wish to disable the crane wing changes however there is no drop down config for the Core setting i can only config the mythic rework
![Screenshot (43)](https://user-images.githubusercontent.com/597204/167176375-7cc28378-2ef6-4a5b-b27f-bbfb9f9ae1e5.png)
s

**Comment by Vek17** [comment]
You do not have the mod installed. Download it here https://github.com/Vek17/TabletopTweaks-Base/releases

**Comment by oddball250** [comment]
oh... im just a big idiot confused base with core :D
