### ISSUE TITLE
Request: Insinuator Antipaladin

### ISSUE THREAD

**Issue by FrijDom** [Vek17/TabletopTweaks-Base#439]
I'd like to see an Insinuator archetype added for your antipaladin, maybe with a similar function to something like the Mixed-Blood Rager, where once a day you choose an alignment (within 1 step of your own) to invoke, and then the class features would work off of that alignment. Since it has the same alignment requirements as your implementation of the antipaladin, I feel it's a great way to make the antipaladin a bit more useful (and with a bit better flavour) for the situation of fighting Demons.

**Comment by Vek17** [comment]
Antipaladin is not part of this mod
