### ISSUE TITLE
The Fix "Rogue Talent Selection" does not allow to select multiple Combat Tricks feats

### ISSUE THREAD

**Issue by danielcs16** [Vek17/TabletopTweaks-Base#444]
I am doing a Skald run, I've selected the feat Combat trick on level 2 and picked Combat Reflexes, now on Level 7 I was expecting to select Combat Trick again and select Seize the Moment, but that option "Rogue Talent Selection" that is inside the Fixes Tab was preventing me to select the Combat Trick feature and I believe that is one those features you can select multiple times.

**Comment by AeonicAssembler** [comment]
The listed fix is "Rogue Talents: Prevents you from selecting the same talent more than once", so what you're experiencing is working as intended by the mod maker.
