### ISSUE TITLE
Armored Might bonus incorrect

### ISSUE THREAD

**Issue by makeshiftwings** [Vek17/TabletopTweaks-Base#450]
My character is at Mythic Rank 4 and took Armored Might. According to the tooltip it should add 50% of the armor bonus up to Mythic Rank / 2 + 1. I'm wearing full plate but only have a bonus of +2, instead of +3.

**Comment by Vek17** [comment]
It is( Mythic Rank + 1) / 2 not (Mythic Rank / 2) + 1

**Comment by makeshiftwings** [comment]
Ah, ok. The tooltip could probably be a little clearer. Thank you!
