### ISSUE TITLE
Undersized mount not working 

### ISSUE THREAD

**Issue by ZebraLan** [Vek17/TabletopTweaks-Base#462]
![image](https://user-images.githubusercontent.com/17749562/181633505-1446e52b-1c7c-4407-92eb-ab87535ce8f7.jpg)
![image](https://user-images.githubusercontent.com/17749562/181633714-62e11b9f-8c50-4611-9165-a168683bfff6.jpg)
![image](https://user-images.githubusercontent.com/17749562/181633997-f3851719-f506-4cde-b373-87643a63d5ee.jpg)
Failed to mount a level 1 boar with a level 1 scared huntsmaster even though she has the undersized mount feat.

**Comment by Vek17** [comment]
You can't mount in town

**Comment by ZebraLan** [comment]
> You can't mount in town
> […](#)

😂first time playing a mounted character. Didn’t know that. My mount attempts actually succeeded once right after respec, so that is actually bugged?

Anyway thanks for replying. Will close issue after testing outside.
