### ISSUE TITLE
Request: Add feats - martial focus and change armor focus to like TT

### ISSUE THREAD

**Issue by Gedeon300W** [Vek17/TabletopTweaks-Base#469]
This option may give us many possibilities to build characters and party.

Just add tabletop version martial focus(https://www.d20pfsrd.com/feats/combat-feats/martial-focus-combat) in a game and made armor focus like tabletop.
(https://www.d20pfsrd.com/feats/combat-feats/armor-focus-combat/)
I mean this part of feat don't exist in game:
The Armor Focus feat counts as the armor training class feature for the purpose of armor mastery feat prerequisites and determines what types of armor you can use with armor mastery feats. Maybe add improved armor focus(https://www.d20pfsrd.com/feats/combat-feats/improved-armor-focus-combat).

Describe alternatives you've considered
No exist.

**Comment by Vek17** [comment]
Armor focus already works this way

**Comment by Gedeon300W** [comment]
Oh, it's my bad. Don't mention in description feat in game.
