### ISSUE TITLE
Animal Aspect suppressing size buffs

### ISSUE THREAD

**Issue by Greyfeld** [Vek17/TabletopTweaks-Base#477]
I've tested this with Enlarge Person and Animal Growth. Any version of Animal Aspect or Greater Animal Aspect cast from my Brown Fur Transmuter Nenio will suppress size-altering buffs on the target. 

I don't have a non-modded game file to test this on, so I can't be 100% sure the issue stems from this mod, but I don't recall having this issue in my first playthrough (which was largely unmodded), and TTT is the only mod I'm running that I can think of that would affect this spell combination, especially since there's a fix that specifically targets polymorph effects and size modifiers from an early patch.

If there's anything specific you need to know, shoot me a message.

**Comment by Vek17** [comment]
Animal aspect is a polymorph effect, and polymorphs suppress size effects

**Comment by Greyfeld** [comment]
Yes, I assumed that was the reasoning behind it. However, if you read the description of the spell, Animal Aspect clearly states that it doesn't affect the size of the target, which means by RAW it shouldn't suppress size effects. And going by RAI, it doesn't make any sense that giving yourself aspects of an animal would suddenly shut off your size-altering affects, especially since you're still considered a humanoid and haven't been affected by any sort of type change that would give you a different template.

Also, I tried disabling the "fix" for polymorph effects overriding size changes, then reboot my game, and it was still suppressing Enlarge Person. So even if I wanted to play without that fix, I can't, because turning it off doesn't actually do anything.

**Comment by Vek17** [comment]
It will stop supressing one the buff ends and you reapply the effect. RAW
all polymorph effects disable size effects.

**Comment by Haplokus** [comment]
Fair enough to make such a ruling.
But since you've made your mod modular, with toggles for most/all aspects, woud you be so kind to make disabling this change actually functional?

**Comment by Vek17** [comment]
It is functional

**Comment by Haplokus** [comment]
Lovely, thank you.
