### ISSUE TITLE
Request: Restore Fighter's Finesse with Mythic Weapon Finesse functionality

### ISSUE THREAD

**Issue by Haplokus** [Vek17/TabletopTweaks-Base#478]
Hello,

The new patch 1.40 has broken the interaction between Fighter's Finesse ("The fighter gains the benefits of the [Weapon Finesse] feat with all melee weapons that belong to the associated fighter weapon group (even if they cannot normally be used with [Weapon Finesse]). The fighter must have the [Weapon Finesse] feat before choosing this option.") and Mythic Weapon Finesse, making only regular Finessable weapons subject to the Mythic Feat and not considering Fighter's Finesse with Weapon Training.

I'd appreciate it if you could restore this functionality, which makes these feats actually valuable to some builds.

Best regards,

/Haplo

**Comment by FrijDom** [comment]
This is a really weird decision on Owlcat's part if it is intentional, as Regill's default build relies on this exact interaction...

**Comment by Haplokus** [comment]
Right. That makes it even weirder.

**Comment by Haplokus** [comment]
Interestingly upon testing, Regill seems immune to this change and still gets Dex to damage with his double hammer.

**Comment by FrijDom** [comment]
What weapon are you testing with otherwise? Perhaps there's an intricacy we're missing.

**Comment by Haplokus** [comment]
I've been intending to use scythes, so Heavy Blade Training. Tested mainly with longswords.
However I've just checked and axes don't work either. Interestingly, Gnome Hooked Hammers ALSO don't work on the MC with Double Weapon Training.

**Comment by FrijDom** [comment]
Good news! As of the latest update, this is no longer a problem.

**Comment by Haplokus** [comment]
True. Fantastic news!
Thank you for your kind interest.
