### ISSUE TITLE
Update 1.4.4g appears to cause game to get stuck on first loading screen with mod

### ISSUE THREAD

**Issue by howardreith** [Vek17/TabletopTweaks-Base#487]
Owlcat pushed an update this morning. Game is now getting stuck at the loading screen. Did some experimenting and it looks like it's TabletopTweaks-Base that's causing it.

With mod disabled

![20220922084526_1](https://user-images.githubusercontent.com/38789146/191751480-a91fcf99-3bf7-4ea5-8fdb-638f8516c79c.jpg)

With mod enabled

![20220922084720_1](https://user-images.githubusercontent.com/38789146/191751520-d9270d4e-1c70-4a84-bea6-0a333719ebbc.jpg)

![20220922084724_1](https://user-images.githubusercontent.com/38789146/191751527-a49c0eee-ec11-4539-a185-062c22b96932.jpg)

Thank you for all your amazing work Vek!

**Comment by seryO-o** [comment]
i have the same issue

**Comment by Vek17** [comment]
You can disable Bloodlines.BloodlineRestrictions and it will work for now. Patch will be out when I get off work in a few hours.
