### ISSUE TITLE
Bug:  Advanced Weapon Training Component breaks Sohei progression 

### ISSUE THREAD

**Issue by Daidre** [Vek17/TabletopTweaks-Base#489]
Sohei can get his first chosen Weapon Group to +2 and +3 at levels 12 and 17, but with  Advanced Weapon Training Component from fighter subgroup that is supposed to enforce requirements, he is treated as someone not meeting prereqs when given a choice at lvl 12 - his only trained  group is grayed out in the list.
As I have checked, Sohei progression works correctly with this component off.

**Comment by Vek17** [comment]
This should be addressed in the next release, which will be for the enhanced edition.
