### ISSUE TITLE
infinite loading screen

### ISSUE THREAD

**Issue by Gwendovescry** [Vek17/TabletopTweaks-Base#491]
After the newest update this one freezes me up at the loading screen. I've gone through every mod combination i had to see if it was interacting poorly with something else. it just won't load up to the main menu anymore

**Comment by howardreith** [comment]
Have you installed the latest version? I raised this issue and I think it's fixed.

https://github.com/Vek17/TabletopTweaks-Base/issues/487

**Comment by Gwendovescry** [comment]
ah i didn't check the discord. i checked everywhere else and didn't see one. completely slipped my mind. thank you

**Comment by Gwendovescry** [comment]
Nope. Still didn't do it for me. I tried disabling bloodline stuff, still won't work

**Comment by Gwendovescry** [comment]
ok I found the right bloodline thing to disable to get it working, but with that running it still doesn't function

**Comment by Vek17** [comment]
If you aren't able to load with v2.3.2 then the issue is almost certainly
not TTT-Base
