### ISSUE TITLE
Request : Option to have old elemental barrage

### ISSUE THREAD

**Issue by PejmanHaghgou** [Vek17/TabletopTweaks-Base#526]
Owlcat has nerfed the elemental barrage bringing it to the "tabletop" level. The thing is I and a lot of people were building toward magus or other classes builds that hinged on this single feat, without it we have to redo our characters, so I wonder if you could add the option to enable the "old" elemental barrage.
thanks

**Comment by Vek17** [comment]
Not in the scope of what this mod does, Reworks has a more powerful version of Elemental barrage but it is not the same as pre nerf barrage (and won't be made to be).
