### ISSUE TITLE
Solid shadow not working.

### ISSUE THREAD

**Issue by Sheshyr** [Vek17/TabletopTweaks-Base#529]
Tested with a char with the mythic Powerful Shadows ability. Using Solid shadow metamagic has no impact.

Solid shadow either :
- does not work at all or
- does not stack with Powerful Shadows.

**Comment by Vek17** [comment]
There is a bug with all hlobal subscriptions atm, looking into it but most
added metamagic are broken along with a few other issues

**Comment by Vek17** [comment]
This should be fixed in https://github.com/Vek17/TabletopTweaks-Core/releases/latest

**Comment by Sheshyr** [comment]
Tested. Shadow effect for shadow enchantment is still 40% instead of 60%.

Do I need to redefine the spell with the metamagic interface?
