### ISSUE TITLE
Armor Master and Armor Training not stacking.

### ISSUE THREAD

**Issue by Arucied** [Vek17/TabletopTweaks-Base#530]
While i understand that eventually armor master mythic ability would eventually outstrip the amount of Dex you could ever achieve (needing over a +14 modifier if it did stack with armor training); but its still odd to me these two don't stack despite otherwise not stating so; as even if they were bonuses they're untyped bonuses.

I say this because i didn't notice at first; doing the midnight isles DLC i noticed this; having gotten to 7th level in fighter and mythic rank 2, I'm only getting +3 Dex from full plate, despite having a +5 modifier; so i should be getting the full +5 if these stacked.

If the intention was for it to not stack could we maybe have a line added to say its not supposed to then? I say as I'd have gotten the first armor training to qualify for advanced armor trainings, but I'd have swapped my 7th level one for an advanced armor training knowing further ranks were wasted.

**Comment by Vek17** [comment]
If you are getting only +3 you probably are at medium encumbrance which results in a hard cap of +3 dex bonus regardless of anything else. These effects do stack as far as I am aware otherwise.

**Comment by Arucied** [comment]
You're right, i missed that; i had just enough equipped to set me over that threshold.
