### ISSUE TITLE
Armored Might - Not Scalling

### ISSUE THREAD

**Issue by SecretOnee** [Vek17/TabletopTweaks-Base#534]
Hello,

I noticed after getting MR2 at the abandoned church that my Armored might was not scaling at all.

I have a +2 Half-plate and in the armor bonus breakdown, armored might is tagged a Focus +1.

![image](https://user-images.githubusercontent.com/118027558/201443686-64cc2730-6202-4940-acba-ee3034d3b12f.png)
![image](https://user-images.githubusercontent.com/118027558/201443773-3cecda88-8986-4cb2-a96f-a479e3d2fe36.png)

I tested adding it to a character with a plate and it would still give only +1 at MR 2. I am running the latest version of the mod and have the 3 of them.

**Comment by Vek17** [comment]
+1 is the correct value at MR 2. The bonus is (1 + Mythic Rank) / 2. This always rounds down. Simplified at MR 2 this 3/2 = 1

**Comment by SecretOnee** [comment]
Then the tooltip seems wrong... it specify half MR +1 not half mythic rank minimum 1.

![image](https://user-images.githubusercontent.com/118027558/201444302-a6171c48-b694-4c8d-909a-bab0b09ccdaf.png)

**Comment by Vek17** [comment]
It is somewhat ambiguous, but there is not a great way to write it without an explicit parenthesis in my opinion which doesn't really look good. It also isn't half mythic rank minimum 1 because at 3 the bonus will be 2 with how the math works and it maxes out at 9.

**Comment by SecretOnee** [comment]
aahhhh!! Ok thank you! I was just confused by the tooltip then! Thank you for your time and i love all you added! Great balance stuff great additions all around!

Have a nice evening!
