### ISSUE TITLE
Infinite Abilities and Turn Based Mode Broken

### ISSUE THREAD

**Issue by Bondoid** [Vek17/TabletopTweaks-Base#548]
Having a significant bug where turn based mode is very slow and enemies take multiple actions in a row. Further my own spells and abilities have infinite uses.

I have only Table Top Tweaks, Toybox, Buy Material Components, and Respec Mod installed.

Anyone have any thoughts on what may be going on?

Thanks for the help!

**Comment by Vek17** [comment]
Its buy material components

**Comment by Bondoid** [comment]
Thanks You! Your a Gentleman and a Scholar!
