### ISSUE TITLE
Can't Start New Game

### ISSUE THREAD

**Issue by Helios-Joe** [Vek17/TabletopTweaks-Base#599]
I made sure to update all my mods, but this one is causing issues on new game. When I try to click past difficulty nothing happens. Been using this mod for ages with no issues until now. I'm assuming it has something to do with the new DLC (I don't have it). Is there any way to still run this mod without the latest DLC?

**Comment by Vek17** [comment]
Dlc should be unrelated, no idea what this could be and I'd need logs to
even guess.

%appdat%/../LocalLow/Owlcat Games/Pathfinder Wrath oc The Righteous

I need player.log and GameLogFull.txt afrer you failed to start.

**Comment by Helios-Joe** [comment]
Ah managed to figure it out my apologies. Must have been some incompatibility between this mod and the respec mod for some reason. Maybe respec broke with the new patch, but I swear it was fine without this mod installed.
