### ISSUE TITLE
BUG: Disabling selective spell tweak for non-instantaneous spells does nothing

### ISSUE THREAD

**Issue by MasterGuyX** [Vek17/TabletopTweaks-Base#603]
Turning off the tweak that disables selective metamagic for non-instantaneous spells doesn't change anything and instead acts like its still turned on. I've tried selective Domain of the Hungry Flesh and selective Black Hole and they still affect my party.

**Comment by Vek17** [comment]
There are three settings that affect selective.

BaseFixes.SelectiveMetamagicNonInstantaneous - Effects the rules of how selective as a mechanic function. This affects a bit more than just spells and is likely what you want to turn off
Feats.SelectiveMetamagic - Removes the metamagic Selective from non instantaneous spells as something that can be applied in the spellbook
Feats.SelectivePrerequisites - Updates the selective metamagic prerequisites

**Comment by MasterGuyX** [comment]
Thanks for the clarification! Didn't know there was that setting in base fixes. I ctrl+F'ed the readme and thought I only needed to turn off Feats.SelectiveMetamagic since that's the only thing that pops up when I search for "selective" or "instantaneous".
