### ISSUE TITLE
Frightful Aspect and Elemental Body spells being supressed.

### ISSUE THREAD

**Issue by Cryostatus** [Vek17/TabletopTweaks-Base#606]
Exactly what the title says; for no apparant reason, those spells are being supressed... I think there might be an issue with the polymorph suppression changes? I'm a Nature Fang, if that changes anything

**Comment by Vek17** [comment]
Do you have any other buffs on you?

**Comment by Cryostatus** [comment]
> Do you have any other buffs on you?

Thanks for the quick reply, and the only other buff I can see on my character is the Commander's Banner. I made sure to remove all my equipment, and disable all my buffs before casting. I've also just checked that it affects any other class I respec into, and it does indeed.

Should I send you a screenshot?

**Comment by Vek17** [comment]
I am not sure what is going on, I cannot reproduce in my test save. Was TTT enabled mid save? If so did you have Icy Body/Firey body applied at the time before you added TTT?

**Comment by Cryostatus** [comment]
> I am not sure what is going on, I cannot reproduce in my test save. Was TTT enabled mid save? If so did you have Icy Body/Firey body applied at the time before you added TTT?

I do have firey body enabled in my save, could that spell be stuck to me somehow?

**Comment by Vek17** [comment]
So most likely the buff is stuck in the suppression part, BUT one that buff wears off and you save/reload it should be purged from the part and everything should work again. Right now the issue is that since owlcat had made it a polymorph spell, and then TTT removed that tag there was a brief period where it could have gotten added to the suppression part and start suppressing size changing buffs (like frightful aspect). The part should be able to clean itself up but it needs the buff to be removed from the character before it can realized that it should no longer treat it as a polymorph spells.

**Comment by Cryostatus** [comment]
Ok thank you! I'll give that a try when I get home, and let you.know how it goes!

**Comment by Cryostatus** [comment]
OK so unfortunately that idea didn't work, and now I'm stumped. I let the firey body wear off, saved, loaded, and then cast Frightful Aspect, but it's still suspended.

**Comment by Vek17** [comment]
If you upload you save I can take a look and see what is stuck

**Comment by Cryostatus** [comment]
Mind telling me how to do that? This is a first for me...

**Comment by Cryostatus** [comment]
I only have a couple supplementary mods too, like Toybox, BubbleBuffs, and Visual Adjustments 2, none of which should cause this

**Comment by Vek17** [comment]
In file explorer put this as the top filepath

%UserProfile%\AppData\LocalLow\Owlcat Games\Pathfinder Wrath of the
Righteous\

There should be s saves foldsr thers

**Comment by Cryostatus** [comment]
Ah, I see the saves, but Github doesn't support me linking my save file? it's a .zks

**Comment by Cryostatus** [comment]
[Manual_33_Thomas.zip](https://github.com/Vek17/TabletopTweaks-Base/files/11074821/Manual_33_Thomas.zip)

OK, hopefully this save works for you

**Comment by Cryostatus** [comment]
Judging by how long it's taken, whatever I've done is bloody niche.

**Comment by Vek17** [comment]
This was a weird issue and I still have no idea what caused it, but I do know it was not specifically TTT. You had a stuck buff suppression like I thought but it was somehow Vanilla's buff suppression system (which unfortunately doesn't let me know what applied it or when). I have fixed the save file however and things should work for it now.
[Manual_33_Thomas.zip](https://github.com/Vek17/TabletopTweaks-Base/files/11080061/Manual_33_Thomas.zip)

**Comment by Cryostatus** [comment]
I see, thank you for fixing the problem despite it not being a problem with your mod! Those spells do indeed seem to work now!
