### ISSUE TITLE
Primalist Second Bloodline Powers

### ISSUE THREAD

**Issue by Schneizeru** [Vek17/TabletopTweaks-Base#609]
As of the recent shifter dlc patch, primalist is supposed be able to choose whether to keep the second bloodline powers or trade them for more rage powers:

> - Fixed the Primalist's level progression for characters with two bloodlines;

The old behaviour persists with the mod enabled; bloodline power is lost without getting the benefits. This is not the case with the mod disabled. I tried to isolate the cause further by browsing the code and toggling off bloodrager related options but that led to nowhere.

**Comment by Schneizeru** [comment]
Serpentine, abyssal, fey. Base game bloodlines.

**Comment by Vek17** [comment]
Not sure what is broken in base game bloodlines as this works when tested, but fixes to second bloodline modded bloodlines are coming in the next release.
