### ISSUE TITLE
Bug: Age category not applying mental bonuses

### ISSUE THREAD

**Issue by notReally47** [Vek17/TabletopTweaks-Base#622]
Tested with only TTT and ToyBox enabled.

Casting Sands of Time (Level 3 Necromancy) and the Witches' hex, Withering, only applies -3 to all physical stats from Old Age. Mental stats are not being applied correctly as per description.

<details><summary>Screenshots</summary>
<p>

![age](https://user-images.githubusercontent.com/112917927/231903116-b59b9f46-6763-4c9d-8c67-4ab073a88ecd.PNG)
![old](https://user-images.githubusercontent.com/112917927/231903977-7e50b5d4-b7e9-4801-9007-d2a996889056.png)
![stats](https://user-images.githubusercontent.com/112917927/231904208-5f0fee24-e18e-4a77-95fe-af94d1f8ff7e.PNG)
</p>
</details>

**Comment by Vek17** [comment]
Sands of time disables ages bonuses as per the description. If you want to
stack age benifits use wither hex again.

**Comment by notReally47** [comment]
Oop, skimmed over Sands of Time while testing Withering hex. Works as intended.
