### ISSUE TITLE
Broken with the new 2.1.5r patch

### ISSUE THREAD

**Issue by Naxterra** [Vek17/TabletopTweaks-Base#672]
I am getting below error on startup after the new patch. I disabled all three mods (Base+Core+Reworks) but then loading from save fails and it gets back to main menu.

![image](https://github.com/Vek17/TabletopTweaks-Base/assets/41871948/8e1eac5e-24a0-4e36-b78e-c9fcde1ae491)

**Comment by Vek17** [comment]
It is an issue in reworks, will fix as soon as I get the chance
