### ISSUE TITLE
Lich Arcanists merged spellbook 

### ISSUE THREAD

**Issue by Lordmitch2** [Vek17/TabletopTweaks-Base#683]
The Lich merged spellbook for the Arcanist gets Inflict Moderate Wounds, Mass on mythic level 3. 
I have no idea if the merged spellbooks for other classes also get Inflict Moderate Wounds, Mass. 
![image](https://github.com/Vek17/TabletopTweaks-Base/assets/47829580/638282f5-1ae6-4b20-a07a-2774ec66421f)

**Comment by Vek17** [comment]
Not sure what you want me to do? This is part of the Lich mythic spellbook.

**Comment by Lordmitch2** [comment]
Merged Spellbooks should only get The mythic spells,  Inflict Moderate Wounds, Mass is not a mythic spell and should only be on the standalone lich spellbook.

**Comment by Vek17** [comment]
That is for owlcat to decide and they put it on the mythic spell list for
Lich

**Comment by Lordmitch2** [comment]
It was probably put on the wrong list by mistake.
