### ISSUE TITLE
Hag of Gyronna Witch (DLC5) cannot choose Second Patron Mythic Ability

### ISSUE THREAD

**Issue by Sikosh1999** [Vek17/TabletopTweaks-Base#690]
Probably because the game never actually assigns this new witch type a patron to begin with, it's impossible to select a second one.

Is there any chance you could make them eligible?

**Comment by Vek17** [comment]
I'll take a look, good catch

**Comment by Vek17** [comment]
Added in hotfix https://github.com/Vek17/TabletopTweaks-Base/releases/tag/v2.6.3
