### ISSUE TITLE
Fighters Finesse

### ISSUE THREAD

**Issue by Ahmiran** [Vek17/TabletopTweaks-Base#691]
Hi, Fighters Finesse doesn't seem to be working with Version 2.6.1
As soon as I activate this mod Regill starts using strength instead of dexterity for his attack.

With the Mod
![20231205223207_1](https://github.com/Vek17/TabletopTweaks-Base/assets/153024649/0ab727db-4ece-4052-a744-ad92429cce6c)

Same save without the Mod enabled
![20231205222833_1](https://github.com/Vek17/TabletopTweaks-Base/assets/153024649/1c51c1fb-7ddd-442e-a45e-039144a8f687)

**Comment by Vek17** [comment]
O.O TTT does not modify Fighter's Finesse at all. No idea how this is occurring but I can replicate. Literally no idea how to fix it right now... I literally never interact with this system wtf

**Comment by Ahmiran** [comment]
Well that's not good. Maybe the issue is in weapon finesse?

**Comment by Vek17** [comment]
Tracked it down and released hotfix https://github.com/Vek17/TabletopTweaks-Base/releases/tag/v2.6.3
