### ISSUE TITLE
Expanded Arsenal fix can not be turned off

### ISSUE THREAD

**Issue by Naruto1135** [Vek17/TabletopTweaks-Base#699]
Expected behavior
Turning off the fix suppose to allow all bonuses from multiple school to add up, but now whether or not the fix is on or off, Expanded Arsenal only take bonus from one other school.

**Comment by Vek17** [comment]
This is something that was changed in vanilla (but not in all cases). So turning it off reverts to vanilla behavior which now does not allow this is most cases.
