### ISSUE TITLE
Metamagic: Elemental: Not giving the descriptor to spell converted.

### ISSUE THREAD

**Issue by SecretOnee** [Vek17/TabletopTweaks-Base#719]
Hello!

It seems that the Metamagic: Elemental does not seems to be working as intended. The damage turns to cold, but the DC seems to be unaffected. Is that normal? My character has Elemental Focus: Cold and the greater one, and none seems to be applied on the converted spell using the metamagic.

I tried with the Elemental bloodline: Water to make sure, if i use the bloodline, then tooltip DC and in combat does get increased.

**Comment by Vek17** [comment]
Elemental spell only changes damage types it does not modify descriptors

**Comment by SecretOnee** [comment]
Awwww, ok thank you for your time!
