### ISSUE TITLE
Disabling "Selective Magic Non Instantanious" has no effect.

### ISSUE THREAD

**Issue by Allyeneedtoknow** [Vek17/TabletopTweaks-Base#734]
Unticking the relevant box option (and restarting!) does not remove the change TTT makes to the Selective Metamagic - it still requires arcane rank 10 and can't be used on duration spells. 

I tested by loading a vanilla save and it still functions like the box was still ticked. Removing TTT and loading the save makes it work normally.

Relative content of the fixes.json reads 
" "SelectiveMetamagicNonInstantaneous": {
        "Enabled": false,
        "Homebrew": false,
        "Description": "Allows only instantaneous effects to be treated as selective by selective metamagic."
      },
"
So it should be disabled, right?

**Comment by Vek17** [comment]
There is a setting in feats that changes prerequistes

**Comment by Allyeneedtoknow** [comment]
Ok , got it thanks! Had googled but only saw stuff but the first check. Problem solved!
