### ISSUE TITLE
natural 20 Critical Confirmation is not Raw so sould not be labled as a fix 

### ISSUE THREAD

**Issue by Gisellle** [Vek17/TabletopTweaks-Base#746]
when you roll a natural 20 you only bypass the ac of the target and hit you do not bypass the confirmation part of a critical hit

"Critical Hits: When you make an attack roll and get a natural 20 (the d20 shows 20), **you hit regardless of your target's Armor Class, and you have scored a “threat,” meaning the hit might be a critical hit (or “crit”).** To find out if it's a critical hit, you immediately make an attempt to “confirm” the critical hit—another attack roll with all the same modifiers as the attack roll you just made. If the confirmation roll also results in a hit against the target's AC, your original hit is a critical hit. (The critical roll just needs to hit to give you a crit, it doesn't need to come up 20 again.) If the confirmation roll is a miss, then your hit is just a regular hit."

https://www.aonprd.com/Rules.aspx?ID=128

sorry to be a rules lawer here but i had to point this out if you are trying to recreate the tabletops rules owl cat had this one right unless there is a pizo ruling to set the RAI differently

**Comment by Vek17** [comment]
I disagree with this reading. Confirmation rolls function exactly the same as attack rolls per RAW. If you read that it says a confirmation is "another attack roll with all the same modifiers as the attack roll". Attack rolls always hit on 20 and thus a confirmation will always confirm on 20 as the attack roll would have hit.

**Comment by Gisellle** [comment]
https://www.aonprd.com/Rules.aspx?ID=97

"Automatic Misses and Hits: A natural 1 (the d20 comes up 1) on an attack roll is always a miss. A natural 20 (the d20 comes up 20) is always a hit. A natural 20 is also a threat—a **possible critical hit** (see the attack action)."

no it dose not modifiers are the statistical modifiers to the to hit roll and AC of the target.
so if you have a +10 do to true strike you have it for both rolls 
not the automatic hit of a nat 20 or the auto miss of a nat 1

**Comment by Vek17** [comment]
I am not sure what you are trying to say with that link. It is explicitly stating that a natural 20 on an attack roll is always a hit. Critical confirmation rolls are **attack rolls** using the same modifiers as the original attacks, and thus always hit on natural 20. 

The stat mofidiers portion of rolls what not what I was highlighting, I was highlighting:

"To find out if it's a critical hit, you immediately make an attempt to “confirm” the critical hit—**another attack roll** with all the same modifiers as the attack roll you just made. **If the confirmation roll also results in a hit** against the target's AC, your original hit is a critical hit. "

Critical Confirmation rolls are explicitly specified to be attack rolls, and thus by the rule you quoted will always be hits on natural 20. Because they are hits, they will always confirm if you roll a natural 20 during critical confirmation.

**Comment by Gisellle** [comment]
it says "a possible critical hit" in the rule for auto hits implying it can fail to crit 
i guess it could be referring to things that stop crits like Windy Escape 
but i don't see it bringing up that concealment could stop the hit from landing after you bypass ac 

if you want the modifiers i can give you them 

[[Combat Modifiers]](https://www.aonprd.com/Rules.aspx?ID=180)

Automatic hits are not a modifier in the rules

**Comment by Vek17** [comment]
Automatic hits are part of the rules for attack rolls, which confirmation rolls ARE. They are refereed this way in every place in the rules that I have seen and thus natural 20's function as automatic hits and thus automatic confirmations. This has nothing to do with combat modifiers or anything of that sort, it is the base rules for attack rolls.

**Comment by Tomykong** [comment]
> I am not sure what you are trying to say with that link. It is explicitly stating that a natural 20 on an attack roll is always a hit. Critical confirmation rolls are **attack rolls** using the same modifiers as the original attacks, and thus always hit on natural 20.
> 
> The stat modifiers portion of rolls what not what I was highlighting, I was highlighting the bolded:
> 
> > To find out if it's a critical hit, you immediately make an attempt to “confirm” the critical hit—**another attack roll** with all the same modifiers as the attack roll you just made. **If the confirmation roll also results in a hit** against the target's AC, your original hit is a critical hit.
> 
> Critical Confirmation rolls are explicitly specified to be attack rolls, and thus by the rule you quoted will always be hits on natural 20. Because they are hits, they will always confirm if you roll a natural 20 during critical confirmation.

this would only work as you describe if the roll to confirm the critical was the same as the roll to hit, which sounds like how you seem to think it works

"If the confirmation roll is a miss, then your hit is just a regular hit." is in the full explanation of the crits

**Comment by Gisellle** [comment]
i'm talking about this on your front page 
Critical Confirmation

    Allows a natural 20 to always confirm a critical.

they don't you still need to roll to confirm a crit so if you roll a nat 20 you then roll to hit to see if you crit in the base rules 

if it would hit normally say a nat15+4 vs 18 ac you crit 
if it hapens to be a nat 20 you crit no mater what there ac is it could be 500 for all it cares 
if it hapens to be a nat 1 you still hit but don't crit no mater what there ac is it could be -1 for all it cares 

by the wording of what you put on the front page it sounded like you don't do the confirm step on a 20 and just confirm it 
i may be mistaken is that reading but thats what i took from it

**Comment by Vek17** [comment]
Yes... So you you roll a natural 20 on the attack, then roll another natural 20 on the attack roll to confirm the critical hits (so 2 consecutive critical hits) then you hit that attack, and confirm that critical hit regardless of the targets AC. I am not saying if you simply roll a natural 20 on your initial attack roll to hit you automatically confirm, I am saying that if you roll a natural 20 during critical confirmation then you confirm that critical regardless of the target's AC.

> Allows a natural 20 to always confirm a critical.

What this means is what I said above, a natural 20 DURING CRITICAL CONFIRMATION will always confirm that critical regardless of the target's AC. In Vanilla Owlcat allows a natural 20 during critical confirmation to miss the target and the critical hit not to confirm. I am not removing any critical confirmation rolls, I am just actually letting natural 20 rolls during critical confirmation to always count as hits and thus always confirm.

**Comment by Gisellle** [comment]
sorry for miss reading it and wasting you time
